export enum AppStep {
  ONBOARDING = 'ONBOARDING',
  DASHBOARD = 'DASHBOARD',
  STUDIO = 'STUDIO',
  GALLERY = 'GALLERY',
}

export interface EntityProfile {
  id: string;
  name: string;
  description: string; // Generated by Gemini
  images: string[]; // Base64
  type: 'PERSON' | 'PRODUCT';
}

export interface AppState {
  user: EntityProfile | null;
  products: EntityProfile[];
  gallery: GeneratedImage[];
  likedPrompts: string[]; // "Memory" of what the user likes
}

export enum GenerationMode {
  USER_ONLY = 'USER_ONLY',
  PRODUCT_ONLY = 'PRODUCT_ONLY',
  COMBINED = 'COMBINED',
}

export interface GeneratedImage {
  id: string;
  url: string;
  prompt: string;
  mode: GenerationMode;
  productId?: string; // Which product was used
  timestamp: number;
  feedback?: 'like' | 'dislike';
}

export interface TrainingData {
  userImages: string[];
  userDescription: string;
  productImages: string[];
  productDescription: string;
  userName: string;
  productName: string;
}